AllCops:
  TargetRubyVersion: 3.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable

  Exclude:
    - "bin/*"

Layout/LineLength:
  Max: 100

Gemspec/DevelopmentDependencies:
  Enabled: false

plugins:
  - rubocop-rspec

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "spec/factories/*.rb"
    - "*.gemspec"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Lint/RedundantCopDisableDirective:
  Exclude:
    - "spec/spec_helper.rb"
